#!/bin/bash
# ============================================================================
# FastVPN — remove idle/never-connected WireGuard peers
# Run this as root on a node VPS (same box running wg0 from setup-wireguard.sh).
#
# A peer counts as "not connected" if:
#   - it has never completed a handshake at all, OR
#   - its most recent handshake is older than MAX_IDLE_SECONDS
#
# Usage:
#   sudo bash remove-idle-peers.sh [max_idle_seconds] [--dry-run]
#   sudo bash remove-idle-peers.sh --install [max_idle_seconds]
#   sudo bash remove-idle-peers.sh --uninstall
#
#   max_idle_seconds defaults to 3600 (1 hour), matching the backend's
#   PENDING_REGISTRATION_MAX_AGE_MS cutoff for peers that never handshaked.
#   Pass a larger value (e.g. 2592000 for 30 days) if you want this to match
#   STALE_REGISTRATION_MAX_AGE_MS behavior for peers that connected before.
#
#   --dry-run   just lists what would be removed, without removing anything.
#   --install   copies this script to /usr/local/sbin and adds a cron job
#               that runs it every 4 hours (logs to /var/log/fastvpn-prune.log).
#               Run this ONCE; after that it's automatic.
#   --uninstall removes the cron job and the installed copy.
# ============================================================================
set -e

WG_IFACE="wg0"
INSTALL_PATH="/usr/local/sbin/remove-idle-peers.sh"
CRON_FILE="/etc/cron.d/fastvpn-prune-peers"
LOG_FILE="/var/log/fastvpn-prune.log"

if [[ "$EUID" -ne 0 ]]; then
  echo "ERROR: must run as root."
  exit 1
fi

if [[ "$1" == "--uninstall" ]]; then
  rm -f "$CRON_FILE" "$INSTALL_PATH"
  echo "==> Removed cron job and installed copy. Auto-pruning disabled."
  exit 0
fi

if [[ "$1" == "--install" ]]; then
  INSTALL_IDLE_SECONDS="${2:-3600}"
  cp -- "$0" "$INSTALL_PATH"
  chmod +x "$INSTALL_PATH"
  cat > "$CRON_FILE" << EOF
# Auto-generated by remove-idle-peers.sh --install
# Runs every 4 hours, removing peers idle longer than ${INSTALL_IDLE_SECONDS}s.
0 */4 * * * root ${INSTALL_PATH} ${INSTALL_IDLE_SECONDS} >> ${LOG_FILE} 2>&1
EOF
  chmod 0644 "$CRON_FILE"
  echo "==> Installed to ${INSTALL_PATH}"
  echo "==> Cron job written to ${CRON_FILE} (runs every 4 hours, idle cutoff=${INSTALL_IDLE_SECONDS}s)"
  echo "==> Logs will go to ${LOG_FILE}"
  echo "==> To remove: sudo bash ${INSTALL_PATH} --uninstall"
  exit 0
fi

MAX_IDLE_SECONDS="${1:-3600}"
DRY_RUN=false

for arg in "$@"; do
  if [[ "$arg" == "--dry-run" ]]; then
    DRY_RUN=true
  fi
done

if ! command -v wg >/dev/null 2>&1; then
  echo "ERROR: 'wg' command not found. Run this on the WireGuard node."
  exit 1
fi

NOW=$(date +%s)

echo "==> Checking peers on ${WG_IFACE} (idle cutoff: ${MAX_IDLE_SECONDS}s)..."

# wg show <iface> dump columns:
# public_key  preshared_key  endpoint  allowed_ips  latest_handshake  transfer_rx  transfer_tx  keepalive
# Skip the first line, which is the interface's own row (no public_key/endpoint fields the same way).
wg show "${WG_IFACE}" dump | tail -n +2 | while IFS=$'\t' read -r PUBKEY _PSK ENDPOINT ALLOWED_IPS LATEST_HANDSHAKE _RX _TX _KEEPALIVE; do
  if [[ "$LATEST_HANDSHAKE" == "0" || -z "$LATEST_HANDSHAKE" ]]; then
    REASON="never connected"
    IDLE_FOR="n/a"
    SHOULD_REMOVE=true
  else
    IDLE_SECONDS=$(( NOW - LATEST_HANDSHAKE ))
    if (( IDLE_SECONDS > MAX_IDLE_SECONDS )); then
      REASON="idle"
      IDLE_FOR="${IDLE_SECONDS}s"
      SHOULD_REMOVE=true
    else
      SHOULD_REMOVE=false
    fi
  fi

  if [[ "$SHOULD_REMOVE" == true ]]; then
    echo "  - ${PUBKEY} (${ALLOWED_IPS}) [${REASON}, idle_for=${IDLE_FOR}]"
    if [[ "$DRY_RUN" == false ]]; then
      # Remove live from the running interface first...
      wg set "${WG_IFACE}" peer "${PUBKEY}" remove
      # ...then strip its [Peer] block from the saved config so it doesn't
      # come back on the next wg-quick up / reboot.
      python3 - "$WG_IFACE" "$PUBKEY" << 'PYEOF'
import sys, re
iface, pubkey = sys.argv[1], sys.argv[2]
path = f"/etc/wireguard/{iface}.conf"
with open(path) as f:
    content = f.read()
# Match this peer's [Peer] block up to (but not including) the next
# [Peer]/[Interface] header or end of file.
pattern = re.compile(
    r"\[Peer\]\n(?:(?!\[Peer\]|\[Interface\]).)*PublicKey = " + re.escape(pubkey) +
    r"\n(?:(?!\[Peer\]|\[Interface\]).)*",
    re.DOTALL,
)
new_content, n = pattern.subn("", content)
if n:
    with open(path, "w") as f:
        f.write(new_content)
PYEOF
    fi
  fi
done

if [[ "$DRY_RUN" == true ]]; then
  echo "==> Dry run complete. No peers were removed."
else
  echo "==> Done."
fi
